<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-61</name>
   <tag></tag>
   <elementGuidId>0a8ee064-b79e-4021-95c0-f0cf38228454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-61</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-61']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad1cacf4-6901-4a87-973d-03f51911d617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-61</value>
      <webElementGuid>ebf4e105-ecef-457a-a8ff-a95052162c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee7fcbb5-fc95-42dd-afe7-3df61d31b702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-61&quot;)</value>
      <webElementGuid>ada18d26-ee0c-4635-ad3a-0087a890cef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-61']</value>
      <webElementGuid>8b3f1edb-aaff-4e42-9362-11239b90b145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[6]/div/div/div/input</value>
      <webElementGuid>ded29484-750f-4349-acfc-c2e7d10e868f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>1ca40afb-474a-4569-b1d3-8c42fa35b230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-61' and @type = 'text']</value>
      <webElementGuid>3ba76864-c0af-4dab-9fe1-c7e868464a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
