<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-46</name>
   <tag></tag>
   <elementGuidId>0c659d1e-280a-4185-9790-1e58e5884132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-46</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-46']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c9c105d-7a90-49d3-8f33-6df62a734b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-46</value>
      <webElementGuid>047ecfff-5782-4b71-ab2e-f6dc348fe32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80061d4b-05bc-4369-b7f2-1b69b12a9ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-46&quot;)</value>
      <webElementGuid>773d5628-ba86-4f72-a099-235e57dfc3b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-46']</value>
      <webElementGuid>b8476307-e3ab-4aa1-94b2-45227dad29da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>d13f21b2-b61c-4db9-85de-b5f6972aadef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d85ae6a3-9766-4484-a2f8-e8a6448b8821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-46' and @type = 'text']</value>
      <webElementGuid>218c3834-da02-4e24-b2b0-79ddb5e46eed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
