<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-58</name>
   <tag></tag>
   <elementGuidId>b7c7159c-0613-427c-a712-8e77d9b782b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-58</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-58']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d21aad4-e530-4262-a1fd-54429e829448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-58</value>
      <webElementGuid>a1c7a110-5e05-4768-b833-f83c623c1d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e330c040-4ad8-452f-ad72-bdfceb551622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-58&quot;)</value>
      <webElementGuid>9d239e74-4783-4555-a2e5-551e65727cdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-58']</value>
      <webElementGuid>b8ba91d1-18c8-4e19-903d-0a1665003519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[5]/div/div/div/input</value>
      <webElementGuid>a837fbd9-3d4b-4d61-a6af-92ac646c347e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>e89c5f6f-8143-4e73-a0f6-a3ef3caaa612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-58' and @type = 'text']</value>
      <webElementGuid>044acf48-c68e-4a31-9f9d-068fddac7035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
