<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-52</name>
   <tag></tag>
   <elementGuidId>286c0924-dfe9-4e41-9531-80c9d153e25b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-52</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-52']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9799c44c-a781-45ac-9dfd-f034a09ebc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-52</value>
      <webElementGuid>416893ee-7827-44d2-97b2-1177a89738f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fa432433-7cec-4bdc-a45c-336130e422fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-52&quot;)</value>
      <webElementGuid>6fac8555-140d-45a2-adbd-2171c0bb2708</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-52']</value>
      <webElementGuid>9b01d6a2-beec-41bc-abb9-c3fe3dd35483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>8a2fe8f6-b301-4951-8c07-067b6d1ae4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>e3c27d2a-9857-400a-baa7-2cd0d4a699b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-52' and @type = 'password']</value>
      <webElementGuid>c494f3f1-e99b-4885-ac78-dedd3d1164bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
