<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Your order has been dispatched, and wil_0578d8</name>
   <tag></tag>
   <elementGuidId>c44a8b9d-4709-4df0-9d14-4316acacbe6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_complete_container']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.pony_express</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>71ad6572-31d6-47b7-89dc-c547c1895cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pony Express</value>
      <webElementGuid>a40f4d3f-e1b4-4883-9c48-d09f4b602e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pony_express</value>
      <webElementGuid>0819ee12-ad55-4ef0-bd02-57729b0365db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/pony-express.46394a5d.png</value>
      <webElementGuid>8d6b6dd9-5400-41f3-87db-7201089f8e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_complete_container&quot;)/img[@class=&quot;pony_express&quot;]</value>
      <webElementGuid>e39b4b32-1b29-466b-96a9-e3516acd76a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout_complete_container']/img</value>
      <webElementGuid>bd28a3e4-2fb2-4414-a019-77986193b43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pony Express']</value>
      <webElementGuid>328a4160-f196-4db2-b6b7-2e7fb09278bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>b268e8fb-ca55-4dea-9bf1-75d0e9b78d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Pony Express' and @src = '/static/media/pony-express.46394a5d.png']</value>
      <webElementGuid>b1dd7083-4523-4690-8c40-d111d78bf238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
