<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-58</name>
   <tag></tag>
   <elementGuidId>647db475-a2dd-4f6a-a778-ad7a89196b99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-58</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-58']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c87c5e4-27dd-4a20-ba1e-ba1d1ea6029b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-58</value>
      <webElementGuid>df356b00-2f4e-4983-879e-29bcd5ac62ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7473ef0d-8349-4051-88a2-c5bf306c1416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-58&quot;)</value>
      <webElementGuid>9652163e-e71d-4f6b-af52-fa9e1fdc9ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-58']</value>
      <webElementGuid>ff238358-97db-46c0-83a0-09ed810fa2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[5]/div/div/div/input</value>
      <webElementGuid>3f9400d7-2bb2-4213-8da9-c589ef12e709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>2e4917ac-5b31-4fe3-bb3a-006b32fc3956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-58' and @type = 'text']</value>
      <webElementGuid>af677de9-7dab-4685-be89-8421dcee7b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
