<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-49</name>
   <tag></tag>
   <elementGuidId>7647b47e-544e-4e19-afb1-655ea83293df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-49</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-49']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf45edac-abf7-4ce4-973b-fc8a779e8d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-49</value>
      <webElementGuid>eeac6b97-bf8c-4b2d-8489-451fcfedbe8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fc5dcb1c-7f8f-4eea-a2ab-0d695dc1c6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-49&quot;)</value>
      <webElementGuid>67e57cdd-80ed-4863-a277-5951faebeffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-49']</value>
      <webElementGuid>640cbe86-b722-4892-82fa-ae542d10785d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>b77cba88-b987-4207-bf0b-5ff9b803a897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>a3d68a80-3b9c-4fe0-9d14-bf1f32d285f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-49' and @type = 'password']</value>
      <webElementGuid>b4864666-7bbf-4c98-96af-3b38d0e84de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
